### PR TITLE
Rename ReadME.md to README.md (for consistency with master)

### PR DESCRIPTION
**Pull request by DaveTryon**
#### Describe the change
Rename ReadME.md to README.md (for consistency with master)

### CODE REVIEW

**Comment by AhmedAbdoOrtiga** [comment]
close to trigger checks

**Comment by DaveTryon** [comment]
Closing/reopening to refresh checks

**Comment by AhmedAbdoOrtiga** [comment]
close and reopen to trigger the checks automatically

**Comment by AhmedAbdoOrtiga** [comment]
@DaveTryon since the checks are tie up to the commit, we will need a new commit to remove those 2 old checks, close and reopen aren't enough, there should be only one check now and it should be triggered automatically

**Comment by DaveTryon** [comment]
Closing, will create a new PR when PR issue is fixed

**Pull request closed without merging**
