### PR TITLE
Add Wildlife Manager to the list of protected code paths for axe-windows

### PR DESCRIPTION
**Pull request by RobGallo**
#### Describe the change

This code will be moved to axe-windows. Therefore, we don't want it modified in the ai-win repo.

#### PR checklist

- [ ] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/master/docs/Scenarios.md) completed?
- [ ] Does this address an existing issue? If yes, Issue# - 
- [ ] Includes UI changes?
  - [ ] Run the production version of Accessibility Insights for Windows against a version with changes.
  - [ ] Attach any screenshots / GIF's that are applicable.

> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass before a merge.

### CODE REVIEW

**Comment by jalkire** [comment]
Given that this app can be useful for testing AI-Win itself, do we want to remove it from here?

**Comment by karanbirsingh** [comment]
> Given that this app can be useful for testing AI-Win itself, do we want to remove it from here?

I agree with @jalkire that this application would be helpful for AI-Win validation & end-to-end tests. One idea he mentioned offline is that each repo seems to require some test app (UI tests vs automation) but it's not strictly necessary those test apps need to be the same.

**Comment by RobGallo** [comment]
> > Given that this app can be useful for testing AI-Win itself, do we want to remove it from here?
> 
> I agree with @jalkire that this application would be helpful for AI-Win validation & end-to-end tests. One idea he mentioned offline is that each repo seems to require some test app (UI tests vs automation) but it's not strictly necessary those test apps need to be the same.

@jalkire  and @karanbirsingh , @DaveTryon  can correct me if I'm wrong, but I believe the test app is critical for unit testing automation. If so, it _must_ be available from the axe-windows repo. And if that is indeed the case, I think it would be better to have the test app in only one place to reduce maintenance cost. if we need a test app for AI-Win that is different from the one we need for axe-windows, we should just create another test app for AI-Win. Thoughts?

**Comment by DaveTryon** [comment]
> From @RobGallo: I believe the test app is critical for unit testing automation. If so, it _must_ be available from the axe-windows repo. 

The check-automation script definitely needs WildlifeManager.exe, so it can't go away at this time. That said, if Axe.Windows were to export the app via NuGet, we could reasonably have AIWin consume that NuGet package. Given the size and scope of the app, it's probably easiest to just have duplicates. That implies that they could get out of sync over time, and we'd have to make some decisions about whether or not we care. My gut is that we don't need to care about drift between the test apps.

**Comment by jalkire** [comment]
@RobGallo I am not arguing that the test app should be excluded from the axe-windows repo. I see this as an opportunity to create a "new" app by duplicating wildlife manager in both repos, but with the intention that they will diverge from this point forward. This would eliminate the maintence concern.

**Comment by RobGallo** [comment]
@jalkire ,

Let's duplicate when we're sure that's what we want to do. In the meantime, it's safe to defer that decision.

**Pull request merged**
