### PR TITLE
Generate thirdpartynotices.html during signed build

### PR DESCRIPTION
**Pull request by jalkire**
#### Describe the change
Currently, we have a manually maintained thirdpartynotices.html file checked into our repo. Updating this file is annoying and easy to forget. This PR updates our signed build loop to generate that file automatically. The file in our repo is updated to be a placeholder for local builds. You can find an example of a generated notice file in the [artifacts of this build](https://dev.azure.com/mseng/1ES/_build/results?buildId=12997829&view=artifacts&type=publishedArtifacts).

[An equivalent PR exists for axe-windows](https://github.com/microsoft/axe-windows/pull/434).

#### PR checklist

- [n/a] Run through of all [test scenarios](https://github.com/Microsoft/accessibility-insights-windows/blob/master/docs/Scenarios.md) completed?
- [n/a] Does this address an existing issue? If yes, Issue# - 
- [n/a] Includes UI changes?
  - [n/a] Run the production version of Accessibility Insights for Windows against a version with changes.
  - [n/a] Attach any screenshots / GIF's that are applicable.

> Note: After the PR has been created, certain checks will be kicked off. All of these checks must pass before a merge.

### CODE REVIEW

**Review by DaveTryon — APPROVED** [review]
_comment deleted_

**Review by DaveTryon — CHANGES_REQUESTED** [review]
Something isn't right here... this looks like the notices file for Axe.Windows, not for AIWin. AIWin should include Axe.Windows, the ADO assemblies, etc.

**Review by DaveTryon — APPROVED** [review]
This is great--should devDependencies (MSTest*, codeCov, coverlet, Moq, Castle.Core, *Analyzers) be filtered out?

Also, it's interesting that there are 2 thirdpartynotices.html in the artifacts. They appear to be identical, but should there be more than one? It looks like axe.windows is only publishing one

**Comment by jalkire** [comment]
> This is great--should devDependencies (MSTest*, codeCov, coverlet, Moq, Castle.Core, *Analyzers) be filtered out?
> 
> Also, it's interesting that there are 2 thirdpartynotices.html in the artifacts. They appear to be identical, but should there be more than one? It looks like axe.windows is only publishing one

The configuration for what gets generated is managed in the [Component Governance portal](https://dev.azure.com/mseng/1ES/_componentGovernance)--I think I have it updated correctly now, but it's a little tricky because the configuration is branch-specific, so I can't know for sure until this is in master. 

For the 2 thirdpartynotices, I believe that happened because I reran failed build steps due to a timeout on signing, so the file got generated/attached twice.

**Pull request merged**
